server:
  port: 8001
spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/seata_demo?useSSL=false&autoReconnect=true&characterEncoding=utf8
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
feign:
  client:
    config:
      default:
        loggerLevel: FULL
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
logging:
  level:
    com.itender.account: debug
seata:
  registry: # TC服务注册中心的配置，微服务根据这些信息去注册中心获取tc服务地址
    # 参考tc服务自己的registry.conf中的配置
    type: nacos
    nacos: # tc
      server-addr: 172.31.25.125:8848
      namespace: 58eed6a7-7fe3-4585-88cd-5223d1924a20
      group: DEFAULT_GROUP
      application: seata-tc-server # tc服务在nacos中的服务名称
      cluster: SH
  tx-service-group: seata-demo # 事务组，根据这个获取tc服务的cluster名称
  service:
    vgroup-mapping: # 事务组与TC服务cluster的映射关系
      seata-demo: SH
  data-source-proxy-mode: AT
#ribbon:
#  eager-load:
#    enabled: true
#    clients: easyexcelService
#logstash:
#  address: 172.31.25.125:4560

#    name: demo
#    url: jdbc:mysql://localhost:3306/demo_01?useSSL=false&autoReconnect=true&characterEncoding=utf8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: root
# mybatis相关配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: false
    use-generated-keys: true
    default-executor-type: REUSE
    use-actual-param-name: true
    # 打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


